spring:
# 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
# JPA配置
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
# 日志配置
logging:
  level:
    root: warn
    com.lzp: info
  file:
    name: log/blog-pro.log
# 指定端口
server:
  port: 8081
